import type { ATSResult } from '@/types'

export const mockATSResult: ATSResult = {
  overallScore: 72,
  matchScore: 68,
  summary: 'Your resume scored 72% overall. 8 of 12 required technical skills matched. 4 keyword gaps identified. Action verbs detected. Add metrics to quantify achievements. ATS compatibility is moderate.',
  candidate: {
    name: 'Alex Johnson',
    role: 'Senior Frontend Engineer',
    company: 'TechCorp Inc.',
    email: 'alex.johnson@email.com',
    phone: '555-0123',
  },
  radarData: [
    { category: 'Keywords', value: 75, fullMark: 100 },
    { category: 'Skills', value: 80, fullMark: 100 },
    { category: 'Experience', value: 65, fullMark: 100 },
    { category: 'Formatting', value: 70, fullMark: 100 },
    { category: 'Sections', value: 85, fullMark: 100 },
    { category: 'Impact', value: 60, fullMark: 100 },
  ],
  highlights: [
    'Contact information is complete and professional',
    'Resume includes all critical ATS sections',
    'Strong technical match: React, TypeScript, Node.js',
    'Uses strong action verbs throughout experience',
  ],
  improvements: [
    'Add missing skills: Docker, GraphQL',
    'Quantify achievements with metrics (percentages, numbers)',
    'Align job titles with target role keywords',
    'Reduce overused keywords: experienced, responsible',
  ],
  platformScores: [
    { name: 'Workday', score: 78, pass: true },
    { name: 'Greenhouse', score: 72, pass: true },
    { name: 'Lever', score: 85, pass: true },
    { name: 'ICIMS', score: 65, pass: false },
  ],
  keywordMatch: {
    matched: ['React', 'TypeScript', 'Node.js', 'JavaScript', 'CSS', 'HTML', 'Git', 'REST'],
    missing: ['Docker', 'GraphQL', 'AWS', 'CI/CD'],
    density: [
      { keyword: 'React', density: 0.8 },
      { keyword: 'TypeScript', density: 0.6 },
      { keyword: 'experienced', density: 0.4 },
      { keyword: 'responsible', density: 0.3 },
    ],
    priority: [
      { keyword: 'Docker', priority: 'high' },
      { keyword: 'GraphQL', priority: 'high' },
      { keyword: 'AWS', priority: 'medium' },
    ],
  },
  skillGap: [
    {
      skill: 'React',
      status: 'matched',
      priority: 'high',
      resource: '',
      importance: 'high',
      evidence: 'Strong experience with React and modern frontend frameworks...',
    },
    {
      skill: 'TypeScript',
      status: 'matched',
      priority: 'high',
      resource: '',
      importance: 'high',
      evidence: 'TypeScript proficiency required for type-safe development...',
    },
    {
      skill: 'Docker',
      status: 'missing',
      priority: 'high',
      resource: 'https://www.google.com/search?q=learn+Docker',
      importance: 'high',
      evidence: 'Containerization experience with Docker is preferred...',
    },
    {
      skill: 'GraphQL',
      status: 'missing',
      priority: 'high',
      resource: 'https://www.google.com/search?q=learn+GraphQL',
      importance: 'high',
      evidence: 'GraphQL API development experience required...',
    },
    {
      skill: 'Node.js',
      status: 'matched',
      priority: 'medium',
      resource: '',
      importance: 'medium',
      evidence: 'Backend development with Node.js and Express...',
    },
    {
      skill: 'AWS',
      status: 'missing',
      priority: 'medium',
      resource: 'https://www.google.com/search?q=learn+AWS',
      importance: 'medium',
      evidence: 'Cloud infrastructure experience on AWS...',
    },
    {
      skill: 'JavaScript',
      status: 'matched',
      priority: 'medium',
      resource: '',
      importance: 'medium',
      evidence: 'Core JavaScript skills for web application development...',
    },
    {
      skill: 'Python',
      status: 'partial',
      priority: 'low',
      resource: 'https://www.google.com/search?q=learn+Python',
      importance: 'low',
      evidence: 'Basic scripting knowledge in Python...',
    },
  ],
  contentAnalysis: {
    measurableResults: [
      {
        text: 'Increased team productivity by 30% through process improvements',
        fix: 'Good — quantified result present',
        reason: 'Metrics strengthen resume impact',
      },
    ],
    spellingGrammar: [],
  },
  formatAnalysis: {
    dateFormatting: { pass: true, detail: 'Date formatting is consistent.' },
    resumeLength: {
      pass: true,
      detail: 'Resume length is appropriate for ATS parsing.',
      tip: 'Keep resume to 1-2 pages for optimal ATS processing.',
    },
    bulletPoints: {
      pass: true,
      suggestions: [],
    },
    headingHierarchy: {
      pass: true,
      detail: 'Section headings are detected and organized.',
    },
    pageCount: {
      pass: true,
      detail: 'Resume length is within optimal 1-2 page range.',
    },
  },
  sectionsAnalysis: {
    sections: [
      { name: 'Name', present: true, value: 'Alex Johnson' },
      { name: 'Email Address', present: true, value: 'alex.johnson@email.com' },
      { name: 'Phone Number', present: true, value: '555-0123' },
      { name: 'LinkedIn', present: true },
      { name: 'Professional Summary', present: true },
      { name: 'Work Experience', present: true },
      { name: 'Education', present: true },
      { name: 'Technical Skills', present: true },
      { name: 'Projects', present: true },
      { name: 'Certifications', present: false },
      { name: 'Achievements', present: true },
      { name: 'Publications', present: false },
      { name: 'Languages', present: false },
      { name: 'Volunteer', present: false },
      { name: 'Internships', present: false },
    ],
  },
  styleAnalysis: {
    voice: {
      pass: true,
      detail: 'Professional tone with action-oriented language.',
      tones: ['professional', 'action-oriented'],
    },
    buzzwords: {
      pass: true,
      suggestions: [],
    },
  },
  skillsAnalysis: {
    hardSkills: [
      { name: 'React', required: true, matched: true, jdCount: 1, resumeCount: 1 },
      { name: 'TypeScript', required: true, matched: true, jdCount: 1, resumeCount: 1 },
      { name: 'Node.js', required: true, matched: true, jdCount: 1, resumeCount: 1 },
      { name: 'Docker', required: true, matched: false, jdCount: 1, resumeCount: 0 },
      { name: 'GraphQL', required: true, matched: false, jdCount: 1, resumeCount: 0 },
      { name: 'AWS', required: false, matched: false, jdCount: 0, resumeCount: 0 },
    ],
    softSkills: [
      { name: 'Leadership', required: false, matched: true, jdCount: 0, resumeCount: 1 },
      { name: 'Communication', required: false, matched: true, jdCount: 0, resumeCount: 1 },
    ],
  },
  deepAnalysis: {
    contactInfo: { score: 100, hasName: true, hasEmail: true, hasPhone: true, hasLinkedin: true },
    resumeSections: { score: 90, found: ['Summary', 'Experience', 'Education', 'Skills', 'Projects'], missing: ['Certifications'] },
    formatting: { score: 75, hasBullets: true, hasConsistentDates: true, properLength: true },
    keywords: { score: 68, matched: ['React', 'TypeScript', 'Node.js', 'JavaScript', 'CSS', 'HTML', 'Git', 'REST'], missing: ['Docker', 'GraphQL', 'AWS', 'CI/CD'], density: [] },
    hardSkills: { score: 67, matched: ['React', 'TypeScript', 'Node.js', 'JavaScript'], missing: ['Docker', 'GraphQL'], totalRequired: 6 },
    softSkills: { score: 80, matched: ['Leadership', 'Communication'], missing: [] },
    experience: { score: 70, totalYears: 6, hasActionVerbs: true, hasQuantifiedResults: false },
    education: { score: 100, hasDegree: true, degreeLevel: "Bachelor's", hasRelevantField: true },
    projects: { score: 80, count: 3, hasDescriptions: true },
    actionVerbs: { score: 75, count: 8, verbs: ['Developed', 'Led', 'Implemented', 'Designed', 'Optimized', 'Built', 'Deployed', 'Managed'] },
    quantifiedAchievements: { score: 40, count: 1, examples: ['Increased team productivity by 30%'] },
    jobTitleMatch: { score: 85, titleOverlap: 70 },
    missingSkills: { score: 50, count: 2, critical: ['Docker', 'GraphQL'] },
    keywordDensity: { score: 70, overused: ['experienced', 'responsible'], underused: ['Docker', 'GraphQL'] },
    duplicateKeywords: { score: 90, count: 2 },
    readability: { score: 85, avgSentenceLength: 14, complexWords: 5 },
    grammar: { score: 95, issues: [] },
    spelling: { score: 100, issues: [] },
    parseConfidence: { score: 90, confidence: 'high', reason: 'Well-structured resume' },
    recruiterFriendliness: { score: 78, hasProfessionalSummary: true, hasQuantifiedResults: false, hasActionVerbs: true, hasConsistentFormatting: true },
  },
  categoryScores: {
    skills: 80,
    experience: 65,
    keywords: 75,
    formatting: 70,
    sections: 85,
    actionVerbs: 60,
  },
}
